#!/bin/sh

NOTIFY_ICON=$POLYBAR/scripts/updates-pacman/packages.svg

format() {
    if [ "$1" -eq 0  ]; then
        echo '-'
    else
        echo "$1"
    fi

}

if ! updates_arch="$(checkupdates | wc -l)"; then
    updates_arch=0
fi

if ! updates_aur="$(yay -Qum 2>/dev/null | wc -l)"; then
    updates_aur=0
fi

updates="$((updates_arch + updates_aur))"

if [ "$updates" -gt 0  ]; then
    echo "  ($(format $updates_arch)/$(format $updates_aur)) "
else
    echo
fi

if hash notify-send &>/dev/null; then
          if (( $updates > 50 )); then
              notify-send -u critical -i $NOTIFY_ICON \
                  "You really need to update!!" "$UPDATES New packages"
          elif (( $updates > 25 )); then
              notify-send -u normal -i $NOTIFY_ICON \
                  "You should update soon" "$UPDATES New packages"
          elif (( $updates > 2 )); then
              notify-send -u low -i $NOTIFY_ICON \
                  "$updates New packages"
          fi
fi

