#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
##
## launch terminal with alt config

CONFIG="$HOME/.config/hypr/foot/foot.ini"
CONFIG1="$HOME/.config/hypr/kitty/kitty.conf"

if [ "$1" == "-f" ]; then
	foot --app-id='foot-float' --config="$CONFIG"
elif [ "$1" == "-F" ]; then
	foot --fullscreen --app-id='foot-full' --config="$CONFIG"
elif [ "$1" == "-s" ]; then
	foot --app-id='foot-float' --config="$CONFIG" \
	--window-size-pixels=$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2 -f "%wx%h")
elif [ "$1" == "-m" ]; then
    kitty --config="$CONFIG1" ranger
else
	foot --config="$CONFIG"
fi
