#!/usr/bin/env bash

# Wayland Specifications
export QT_SCALE_FACTOR=1
export SDL_VIDEODRIVER4=wayland
export XDG_CURRENT_DESKTOP=Hyprland
export WLR_DRM_DEVICES=/dev/dri/card0
#export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=gtk3
export GDK_BACKEND=x11
