#!/bin/bash

#Set bg
#xwallpaper --output DisplayPort-2 --zoom "$HOME/.config/sxiv/external.png" --output DisplayPort-1 --zoom "$HOME/.config/sxiv/external.png" &



#BSPWM configuration
bspc config border_radius       9
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          60
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config single_monocle       false
#set cursor
xsetroot -cursor_name left_ptr
# bspc config click_to_focus       true
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
#bspc config pointer_action1  move
#bspc config pointer_action1 resize_side
#bspc config pointer_action3 resize_corner
# bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#1f3442"
bspc config active_border_color		"#92aec7"
bspc config focused_border_color	"#4d9194"
bspc config presel_feedback_color	"#000000"
#bspc config urgent_border_color 	"#dd2727"


#BSPWM layout
bsp-layout set tall 1
bsp-layout set tall 2
bsp-layout set rgrid 3
#bsp-layout set rgrid 4
#bsp-layout set rgrid 5
#bsp-layout set tall 6
#bsp-layout set rwide 7
#bsp-layout set rwide 8
#bsp-layout set rwide 9


#monitor setup
bspc monitor eDP -d 1 2 3 4 5
bspc monitor  DisplayPort-1 -d 6 7 
bspc monitor  DisplayPort-2 -d 8 9
bspc wm -O eDP DisplayPort-1 DisplayPort-2

#Fullscreen applications
bspc rule -a Vlc state=fullscreen

#Floating applications
declare -a floats=(Arandr feh Font-manager Galculator \
Gpick Nitrogen Pavucontrol Stacer Pavucontrol Virt-manager \
Lxapperance Sxiv)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating; done

# bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window

$HOME/.config/bspwm/autostart.sh &

